name: UrlShortener CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASS }}
      DB_HOST: ${{ secrets.DB_HOST }}

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Test MySQL Connection
        run: |
          echo "Testing MySQL connection..."
          mysql -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USER }} -p"${{ secrets.DB_PASS }}" -e "SELECT 'Connected successfully' AS Status;"

      - name: Run tests
        run: npm test
