name: UrlShortener CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASS }}
      DB_HOST: ${{ secrets.DB_HOST }}

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Test MySQL Connectivity
        run: |
          $mysqlCommand = @"
          mysql -h $env:DB_HOST -u $env:DB_USER -p"$env:DB_PASS" -e "SELECT 'Connected successfully' AS Status;"
          "@
          Invoke-Expression -Command $mysqlCommand
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}

      - name: Run tests
        run: npm test
